name = "hugoMTTRelease"
baseURL = "https://hugo-minimal-test-theme-demo.wildgarden.ca/"
description = "Modules for Hugo Minimal Test Theme Release Version (for building actual sites not just for testing)"

[module]
  [module.hugoVersion]
    min = "0.81.0"
    extended = false

  [[module.imports]]
     path = "git.wildtechgarden.ca/danielfdickinson/hugoDebugTables"

[author]
  name = "Daniel F. Dickinson"
  homepage = "https://www.danielfdickinson.ca"
  copyright = "© 2021 Daniel F. Dickinson"
